### ISSUE TITLE
blue screen after 5 seconds

### ISSUE THREAD

**Issue by dakota72** [danimartin82/opencv_raylib#1]
Hi,
I tried your test2_camera with raspberry pi 3
and after 5 seconds, the screen became blue and the video don't appear.
I tried also to change input frame with a raspberry camera 5Mpx and the behavior
is the same.
regards and compliments for your work.
Giampaolo.

**Comment by danimartin82** [comment]
Hi Giampaolo! I'm glad my work can be useful.

In your case I would go step by step. 
* Are you able to reproduce the video with a normal video player? And the camera? Just to be sure that it's not an issue with codecs or OS.

* I would try to reproduce the frames captured without any processing. In test2_camera code, frames2.  Here it is a ver well explained example:
https://www.learnopencv.com/read-write-and-display-a-video-using-opencv-cpp-python/

* If the frames are displayed ok, then the issue is in the processing. Perhaps in the conversion from OpenCV to raylib? Or in the thresholds...

**Comment by dakota72** [comment]
Hi Martin,
thanks for the reply
> * Are you able to reproduce the video with a normal video player? And the camera? Just to be sure that it's not an issue with codecs or OS.

yes, I tried your video1.avi with vlc and works very well

> * I would try to reproduce the frames captured without any processing. In test2_camera code, frames2.  Here it is a ver well explained example:

yes, and it works very well, also I tried to change 
cv::VideoCapture cap("video1.avi");
with
cv::VideoCapture cap(0);
and also works very well. 

> * If the frames are displayed ok, then the issue is in the processing. Perhaps in the conversion from OpenCV to raylib? Or in the thresholds...

I tried your test1_image.cpp and it works, therefore your conversion from OpenCV to raylib texture works.

	image_raylib.width = image_cv_rgb.cols;
	image_raylib.height = image_cv_rgb.rows;
	image_raylib.format = UNCOMPRESSED_R8G8B8;
	image_raylib.mipmaps= 1 ;
	image_raylib.data= (void*)(image_cv_rgb.data);
	
	Texture2D texture = LoadTextureFromImage(image_raylib);      // Image converted to texture, uploaded to GPU memory (VRAM)

In my example I changed video1.avi with cam(0) and disabled all processing, the video appear for 3 sec, next the screen became all black or blue.  Maybe the video memory lost a pointer ...

this is my code (99,9% danimartin82)

#include <stdio.h>
#include <iostream>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/core/utility.hpp>

#include <opencv2/core.hpp>

#include "raylib.h"

using namespace std;

int main(int argc, char** argv)
{
        cv::Mat frame1;
	cv::Mat frame2;
	cv::Mat frame_diff;
	cv::Mat frame_gray;
	cv::Mat frame_blurr;
	cv::Mat frame_thresh;
	cv::Mat frame_dilated;
	cv::Mat framergb;
	vector<vector<cv::Point>> array_contours;
	std::vector <Rectangle> vector_of_rectangles;
        Image image_raylib;

	int screenWidth;
	int screenHeight;
	
	//--------------------------------------------------------------------------------------
	// open the default camera
	//--------------------------------------------------------------------------------------
	//cv::VideoCapture cap("video1.avi");
	cv::VideoCapture cap(0);
	if (!cap.isOpened())
	{
		printf("ERROR Cannot open video\n");
	}


	cap >> frame2;

	//--------------------------------------------------------------------------------------
	// Init Raylib window
	//--------------------------------------------------------------------------------------
	screenWidth = frame2.cols;
	screenHeight = frame2.rows; 

	InitWindow(screenWidth, screenHeight, "raylib opencv test2: camera");
	SetTargetFPS(30);


	//--------------------------------------------------------------------------------------
	// Convert from OpenCV to Raylib
	//--------------------------------------------------------------------------------------
	 
	cv::cvtColor(frame2, framergb, cv::COLOR_BGR2RGB);
	image_raylib.width = framergb.cols;
	image_raylib.height = framergb.rows;
	image_raylib.format = UNCOMPRESSED_R8G8B8;
	image_raylib.mipmaps= 1 ;
	image_raylib.data= (void*)(framergb.data);
	
	Texture2D texture = LoadTextureFromImage(image_raylib);      // Image converted to texture, uploaded to GPU memory (VRAM)

	SetTraceLogLevel(LOG_NONE);
			
	// Main loop
	while (!WindowShouldClose())    // Detect window close button or ESC key
	{
		cv::cvtColor(frame2, framergb, cv::COLOR_BGR2RGB);

		image_raylib.data = (void*)(framergb.data);
	        image_raylib.width = framergb.cols;
                image_raylib.height = framergb.rows;
 	        image_raylib.format = UNCOMPRESSED_R8G8B8;
	        image_raylib.mipmaps= 1 ;

		Texture2D texture = LoadTextureFromImage(image_raylib);

		// Draw
		//----------------------------------------------------------------------------------
		BeginDrawing();

		ClearBackground(RAYWHITE);
                DrawTexture(texture, 0, 0, WHITE);
		
		EndDrawing();
		//----------------------------------------------------------------------------------

		//cap.read(frame2);
		cap >> frame2;
		if (frame2.empty())
		{
			break;

		}
	
	}

        UnloadTexture(texture);
	CloseWindow();        // Close window and OpenGL context
	//--------------------------------------------------------------------------------------

    return 0;
}


regards,
Giampaolo.

**Comment by danimartin82** [comment]
Just to confirm, have you try test2_camera.cpp as it is?
 I would sugest to try it. 

Another suggestion is to remove "SetTraceLogLevel(LOG_NONE);" This will alloy raylib to generate debug info in the console. Yo can debug frame by frame or start debugging when you are close to 3 seconds (just add a frame counter and an if condition to execute a line of code if frame counter is bigger than a specific number. Then, add a breakpoint in tha line).

At least this have to show you where is the problem. 

regarding your code....I see a couple of things:
* you have an strange empty "#include". Probably it is not affecting, but anyway it doesn't make sense.
* I added "frame2.release();" at the end of the loop. Perhaps you can add it and give a try,

Regards

**Comment by dakota72** [comment]
Hi Martin,
sorry for late answer but the issue was very difficult to resolve,
but finally I have found the solution.

when you call 		
Texture2D texture = LoadTextureFromImage(image_raylib);
the texture fill the vram of the gpu, when it is full the screen will came black.
for this reason the call:
    UnloadTexture(texture);
must be inserted into a main loop, after enddrawing
probably you don't see the problem because the pc have a big vram memory,
but the raspberry is smaller than pc and the problem came early.
thanks for you help (and for your code ;) )

Giampaolo alias dakota.

**Comment by danimartin82** [comment]
Thanks for the feedback. Indeed this UnloadTexture(texture); is in test3.....but it was missing in test2. I have fixed it.

Thanks!!! :-)
